Updated the cpp code to catch the ctrl_c interruption. Fix for issue #21.
ThrunGroup/BanditPAM pull request #104
Opened 2021-07-30 19:25 UTC by dhaval737

This is the fix for issue #21.

- Modified the file `kmedoids_ucb.cpp` and added the method `signal_callback_handler`  for signal handling. 
- If CPP code is being executed and code gets the `ctrl+c` signal, it will execute this method to terminate the running process.
- This code is only handle the `ctrl+c` event when CPP code is running. I noticed that in the test cases we are reading large csv files in python code and it takes a while to finish that execution. This code does not handle that situation.
- Test case : If I am executing the test cases or any other examples and CPP code is taking a long time, if i give `ctrl+c` my process gets killed immediately with the message `^CCaught signal 2`

2021-07-30 22:49 UTC, motiwari requested changes
This is a very helpful feature; thank you for implementing it. Some nits in the review.

2021-07-30 22:49 UTC, motiwari commented on src/kmedoids_ucb.cpp
> + * If signal is received it kilss the process.
nit: `kilss`
Also, move to 1 line if it fits within 80 char limit, otherwise OK

2021-07-30 22:49 UTC, motiwari commented on src/kmedoids_ucb.cpp
> +   // Terminate program
unnecessary comment

2021-07-30 22:49 UTC, motiwari commented on src/kmedoids_ucb.cpp
> +void KMedoids::fit(arma::mat input_data, std::string loss) {
remove extraneous whitespace at EOL (for future, can configure a linter automatically to do this)

2021-07-30 22:49 UTC, motiwari commented on src/kmedoids_ucb.cpp
> +
rm

2021-07-31 00:10 UTC, dhaval737 commented
@motiwari I have updated the code as per comments.

2021-07-31 23:06 UTC, dhaval737 commented on src/kmedoids_ucb.cpp
> +
Removed the extra line

2021-08-04 14:26 UTC, merged