add version attribute to python module. Fixes #63
ThrunGroup/BanditPAM pull request #67
Opened 2021-07-05 03:31 UTC by mailology

Add version attribute in pybind module `PYBIND11_MODULE(BanditPAM, m)` for the version of python package. The version number follows the value of `__version__` in `setup.py` file. 

The current version of this package is 
<img width="346" alt="Screen Shot 2021-07-04 at 11 18 01 PM" src="https://user-images.githubusercontent.com/25496074/124413159-166e0b00-dd1e-11eb-89bf-20e1b0e57803.png">

The update follows an example for version attribute from pybind doc: https://github.com/pybind/python_example/blob/master/src/main.cpp

The following 2 lines are used to covert a macro argument `VERSION_INFO` to a string constant:
```
#define STRINGIFY(x) #x
#define MACRO_STRINGIFY(x) STRINGIFY(x)
```
and here is the reference: https://gcc.gnu.org/onlinedocs/cpp/Stringizing.html#Stringizing

2021-07-05 14:21 UTC, motiwari requested changes
A good PR name with automatic issue closure and a thorough commit message with screenshot of test plan and link to example -- nice work, @mailology ! 

Small nits on whitespace and then should be good to merge.

2021-07-05 14:21 UTC, motiwari commented on src/kmeds_pywrapper.cpp
> +    m.attr("__version__") = MACRO_STRINGIFY(VERSION_INFO);
nit: same indentation level as `m.doc` above

2021-07-05 14:21 UTC, motiwari commented on src/kmeds_pywrapper.cpp
> +    m.attr("__version__") = "dev";
nit: same indentation level as `m.doc` above

2021-07-06 04:14 UTC, mailology commented
Adjust the indentation level of `m.doc`.

2021-07-07 16:31 UTC, merged